### ISSUE TITLE
about "split_func_path" file

### ISSUE THREAD

**Issue by Ruturaj4** [shensq04/EKLAVYA#8]
I am struggling with the RNN training step. Are we suppose to create - "split_func_path"  file?
If so, could you please help me out with this? I felt that the instructions are unclear. I also read the paper. I saw the given examples. But, I am pretty much stuck on this step. I know, this paper is published long ago, but do you have any hints on this? Your help is much appreciated.

**Comment by qingbol** [comment]
Yes, you need to create  "split_func_path" file. You can write a script to extract that information from dataset file.

**Comment by Ruturaj4** [comment]
> Yes, you need to create "split_func_path" file. You can write a script to extract that information from dataset file.

@quigbol

Thanks. I appreciate your reply. I have few more questions -

1) Type of file (should it exactly be as the description says - sort of a dictionary, or it should be "picked")
2) Is binary_file_name == path + binary_file_name
3) what if there are multiple functions in the binary

**Comment by Ruturaj4** [comment]
nvm I got it :-)
